name: Basic Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        mkdir -p $ANDROID_SDK_ROOT
        cd $ANDROID_SDK_ROOT
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/ 2>/dev/null || true
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        yes | sdkmanager --licenses || true
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
    
    - run: npm ci
    - run: npm run build
    - run: npx cap sync android
    
    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon
        
    - uses: actions/upload-artifact@v4
      with:
        name: quantum-risk-coach-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        
    - uses: softprops/action-gh-release@v1
      if: success()
      with:
        tag_name: v${{ github.run_number }}
        name: "Quantum Risk Coach APK v${{ github.run_number }}"
        body: |
          🎉 **SUCCESS! Your Quantum Risk Coach APK is ready!**
          
          📱 **Download the APK file below and install on your Android device**
          
          ### Installation:
          1. Download the APK file
          2. Enable "Install from unknown sources" on your Android device
          3. Install the APK
          4. Launch the Quantum Risk Coach app!
        files: android/app/build/outputs/apk/debug/app-debug.apk 