name: Basic Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: cimg/android:2024.01.1-node
    
    steps:
    - uses: actions/checkout@v4
        
    - run: npm ci
    - run: npm run build
    - run: npx cap sync android
    
    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace --info
        
    - uses: actions/upload-artifact@v4
      with:
        name: apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        
    - uses: softprops/action-gh-release@v1
      if: success()
      with:
        tag_name: basic-${{ github.run_number }}
        files: android/app/build/outputs/apk/debug/app-debug.apk 