name: Basic Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: npm
    
    - uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 29
        target: default
        arch: x86_64
    
    - run: npm install
    - run: npm run build
    - run: npm install -g @capacitor/cli
    - run: npx cap add android --confirm || echo "Android platform already exists"
    - run: npx cap sync android
    
    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew clean
        ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: quantum-risk-coach-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 90
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: success()
      with:
        tag_name: success-v${{ github.run_number }}
        name: "✅ Quantum Risk Coach APK v${{ github.run_number }} - READY FOR DOWNLOAD!"
        body: |
          # 🎉 SUCCESS! Your Quantum Risk Coach APK is Ready!
          
          ## 📱 DOWNLOAD YOUR APK NOW:
          **Click on the APK file below to download directly to your device**
          
          ## 📋 Installation Instructions:
          1. **Download** the APK file below
          2. **Enable "Unknown Sources"** in your Android settings
          3. **Install** the APK on your device  
          4. **Launch** Quantum Risk Coach!
          
          ## ✨ Features Included:
          - Complete trading coach application
          - Advanced risk management tools
          - Real-time market analysis
          - AI-powered trading insights
          - Mobile-optimized interface
          
          ---
          **Build ID:** ${{ github.run_number }} | **Status:** ✅ SUCCESS
        files: android/app/build/outputs/apk/debug/app-debug.apk
        draft: false 