name: Ionic Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build app
      run: npm run build
      
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
        
    - name: Add Capacitor Android platform
      run: |
        npm install -g @capacitor/cli @ionic/cli
        npx cap add android --confirm
        
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Build APK
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleDebug --no-daemon --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: quantum-risk-coach-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: success()
      with:
        tag_name: ionic-v${{ github.run_number }}
        name: Quantum Risk Coach APK v${{ github.run_number }}
        body: |
          📱 Quantum Risk Coach APK Build v${{ github.run_number }}
          
          ### Download APK:
          - Click on the APK file below to download
          - Install on your Android device
          
          ### Features:
          - Complete trading coach application
          - Risk management tools
          - Market analysis
          - AI-powered insights
        files: android/app/build/outputs/apk/debug/app-debug.apk
        draft: false
        prerelease: false 